name: ROS 2 CI

on:
  push:
  pull_request:

jobs:
  ros2:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ROS 2 Jazzy
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Install ROS dependencies
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          rosdep install \
            --from-paths ros2_ws/src \
            --ignore-src \
            --rosdistro jazzy \
            -r -y

      - name: Build ROS workspace
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          cd ros2_ws
          colcon build --symlink-install

      - name: Test ROS workspace
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          cd ros2_ws
          colcon test
          colcon test-result --verbose
